"""empty message

Revision ID: 140da7745c73
Revises: 
Create Date: 2021-03-02 23:08:47.538788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140da7745c73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('altura', sa.String(length=250), nullable=True),
    sa.Column('masa', sa.String(length=250), nullable=True),
    sa.Column('pelo', sa.String(length=250), nullable=True),
    sa.Column('piel', sa.String(length=250), nullable=True),
    sa.Column('ojos', sa.String(length=250), nullable=True),
    sa.Column('nacimiento', sa.String(length=250), nullable=True),
    sa.Column('genero', sa.String(length=250), nullable=True),
    sa.Column('creado', sa.String(length=250), nullable=True),
    sa.Column('editado', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('diametro', sa.String(length=250), nullable=True),
    sa.Column('periodo_rotacion', sa.String(length=250), nullable=True),
    sa.Column('periodo_orbital', sa.String(length=250), nullable=True),
    sa.Column('gravedad', sa.String(length=250), nullable=True),
    sa.Column('poblacion', sa.String(length=250), nullable=True),
    sa.Column('clima', sa.String(length=250), nullable=True),
    sa.Column('terreno', sa.String(length=250), nullable=True),
    sa.Column('superficie_acuatica', sa.String(length=250), nullable=True),
    sa.Column('creado', sa.String(length=250), nullable=True),
    sa.Column('editado', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=250), nullable=False),
    sa.Column('apellido_1', sa.String(length=250), nullable=False),
    sa.Column('apellido_2', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password')
    )
    op.create_table('Favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('personajes_id', sa.Integer(), nullable=True),
    sa.Column('planetas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personajes_id'], ['Personajes.id'], ),
    sa.ForeignKeyConstraint(['planetas_id'], ['Planetas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Favoritos')
    op.drop_table('Usuarios')
    op.drop_table('Planetas')
    op.drop_table('Personajes')
    # ### end Alembic commands ###
